services:
    app:
        build: .
        container_name: portfolio_app
        working_dir: /var/www/html
        volumes:
            - "./:/var/www/html"
            - "views_cache:/var/www/html/storage/framework/views"
            - "bootstrap_cache:/var/www/html/bootstrap/cache"
        env_file:
            - .env
        networks:
            - app-network
        depends_on:
            - db
        ports:
            - "9000:9000"

    web:
        image: "nginx:alpine"
        container_name: portfolio_web
        volumes:
            - "./:/var/www/html"
            - "./nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8080:80"
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: "postgres:15"
        container_name: portfolio_db
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: portfolio
        ports:
            - "5433:5432"
        networks:
            - app-network
        volumes:
            - "db_data:/var/lib/postgresql/data"

networks:
    app-network:
        driver: bridge

volumes:
    db_data: {}
    views_cache: {}
    bootstrap_cache: {}
