version: "3.8"
services:
    app:
        build: .
        container_name: portfolio_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - app-network
        depends_on:
            - db
        ports:
            - "9000:9000"

    web:
        image: nginx:alpine
        container_name: portfolio_web
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: postgres:15
        container_name: portfolio_db
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: portfolio
        ports:
            - "5433:5432"
        networks:
            - app-network
        volumes:
            - db_data:/var/lib/postgresql/data # データ永続化のためのボリュームマウント

networks:
    app-network:
        driver: bridge

volumes:
    db_data: {} # db_dataボリュームをここで定義する
